config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "users#index"
  resources :courses
  resources :enrollments
  resources :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_secure_password

  enum status: { active: "active", inactive: "inactive" }, _default: "inactive"

  validates :name, presence: true
  validates :mobile, presence: true, uniqueness: true, length: { minimum: 10, maximum: 10 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9\-\.]+[@][a-z]+[\.][c][o][m]\z/, message: "Please Enter Email Like Example123@gmail.com" }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/views/users/index.html.erb
<%= stylesheet_link_tag "style" %>

<center>
<div>
  <% if !current_user.nil? && current_user.type == "Teacher" %>
    <button>   <%= link_to "Create Course", new_course_path  %></button>
    <button>  <%= link_to "All Courses" , courses_path %></button>

  <% elsif !current_user.nil?  %>
    <button>  <%= link_to "All Courses" , courses_path %></button>
    <button>  <%= link_to "All Cetegories" , categories_path %></button>
  <% elsif current_user.nil? %>
    <button>  <%= link_to "Login" , "users/sign_in" %></button>
    <button> <%= link_to "Sign Up", "users/sign_up" %> </button>

  <% end %>
  <% if !current_user.nil? && current_user.type == "Student" %>
    <button> <%= link_to "Enroll", new_enrollment_path %> </button>
  <% end %>
  <%= button_to "LogOut", destroy_user_session_path,method: :delete%>
</div>

</center>

app/views/users/new.html.erb
<%= stylesheet_link_tag "style" %>

<center>
  <h1>Registration</h1>
<div style="border: 1px solid black; width:240px; background-color: gainsboro;">
<br>
<%= form_with model: @user do |form| %>
<div>
  <%= form.label :name %><br>
  <%= form.text_field :name , placeholder: "Enter Name"%>
</div>

<div>
  <%= form.label :email  %><br>
  <%= form.email_field :email, placeholder: "Enter Email" %>
</div>

<div>
  <%= form.label :mobile  %><br>
  <%= form.text_field :mobile, placeholder: "Enter Mobile Number" %>
</div>

<div>
  <%= form.label :password  %><br>
  <%= form.password_field :password , placeholder: "Enter Password"%>
</div>

<div>
  <%= form.label :User_type  %><br>
  <%= form.select :type, ["Teacher", "Student"] %>
</div>
<br>
<div>
  <%= form.submit "Sign Up"%>
</div>
<% end %>
</div>

</center>

app/views/users/show.html.erb
<!-- <h1>Registration</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email  %><br>
    <%= form.email_field :email %>
  </div>
  <div>
      <%= form.label :mobile  %><br>
      <%= form.number_field :mobile %>
    </div>
  <div>
      <%= form.label :password  %><br>
      <%= form.password_field :password %>
    </div>
  <div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
 -->